<script setup>
const { matchHist } = defineProps(["matchHist", "sumId"])
const matchHistData = ref(null)
const loading = ref(true)

function resolvePromise() {
  matchHist
    .then((res) => {
      matchHistData.value = res
      loading.value = false
    })
    .catch((err) => {
      console.log("Error on resolving match data Promise")
    })
}

onMounted(() => {
  resolvePromise()
})
</script>

<template>
  <div v-if="loading">
    loading matchData:
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        margin: auto;
        background: none;
        display: block;
        shape-rendering: auto;
      "
      width="200px"
      height="200px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <rect x="21" y="39" width="8" height="22" fill="#8ec07c">
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="1s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="32.4;39;39"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.2s"
        ></animate>
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="1s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="35.2;22;22"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.2s"
        ></animate>
      </rect>
      <rect x="46" y="39" width="8" height="22" fill="#8ec07c">
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="1s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="34.05;39;39"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.1s"
        ></animate>
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="1s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="31.900000000000006;22;22"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.1s"
        ></animate>
      </rect>
      <rect x="71" y="39" width="8" height="22" fill="#8ec07c">
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="1s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="34.05;39;39"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        ></animate>
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="1s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="31.900000000000006;22;22"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        ></animate>
      </rect>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
  <main
    class="px-8 py-4"
    v-if="matchHistData"
    v-for="(match, index) in matchHistData"
  >
    <Match :matchData="match" :index="index" :sumId="sumId" />
  </main>
</template>
